version: "3.8"

services:
  # Real-Time Chat Application
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: real-time-chat-app
    restart: unless-stopped
    ports:
      - "3000:3000" # HTTP server port
      - "4000:4000" # WebSocket server port
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=*
    volumes:
      - ./logs:/app/logs # Mount logs directory
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
