version: "3.8"

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: real-time-chat-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "4000:4000"
      - "4001:4001" 
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs